import { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./components/Providers";

export const metadata: Metadata = {
  title: "W3lcome",
  description: "Generated by create turbo",
};

interface Props {
  modal: ReactNode
  children: ReactNode
}

export default async function RootLayout({
  children,
  modal
}: Props) {
  return (
    <html lang="en">
      <Providers>
        <body className="w-screen h-screen">
          {children}
          {modal}
        </body>
      </Providers>
    </html>
  );
}
