import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "W3lcome",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">{children}</body>
    </html>
  );
}
